### ISSUE TITLE
Classify genius artists as rappers (or not)

### ISSUE THREAD

**Issue by heus92** [Rapacademix/redbull#3]
The Genius DB is very rich... maybe too rich. Thus not all the artists we got from their API are rappers. We need to find a way to classify them in order to keep rappers as part of our core dataset.

Fortunately, Genius artists come with a `description` field in the JSON the API returns. We are going to use this field to offer the first classification. 

ToDo
- [x] create `description` text field in the `api_artists`table (*i.e.* add it to the related `Artist`model) 
- [x] create `is_rapper` boolean in the `api_artists`table (*i.e.* add it to the related `Artist`model) 
- [x] create the `why_is_rapper` text field in the `api_artists` table (*i.e.* add it to the related `Artist`model) to store the word that triggered `Artist.is_rapper = True`
- [x] run @LouisonGitzinger's script that converts the description we got from all API calls into plain text and insert plain descritpion in  newly created `description` field
- [ ] run @heus92's script that analyses the plain description to return the `is_rapper` boolean valuen **and** the `why_is_rapper` word that possibly triggered `Artist.is_rapper = True`

Is that ok with you guys ?

**Comment by LouisonGitzinger** [comment]
- Instead of `why_is_rapper` I suggest `genre_keywords`.
- It means that the `why_is_rapper` can be `null` (it does not matter).
- Maybe we should create a table that holds all the vocabulary used for classification.

**Comment by LouisonGitzinger** [comment]
`json`to `plain_text` descriptipn method:
```python
def get_plain_text(children):
	plain_text = ""
	for item in children:
		if isinstance(item, str):
			plain_text += item
		elif isinstance(item, dict):
			if 'children' in item:
				plain_text += get_plain_text(item['children'])
	return plain_text
```

**Comment by heus92** [comment]
- `genre_keywords` is a way better naming indeed
- question you use plural with `genre_keywords` and not singular `genre_keyword`. Does that mean that you'd like us to store all matches ? Because the function I wrote down (that can be modified of course) stops after the first match
- `null` type is 👍 
- why not ¯\_(ツ)_/¯

**Comment by heus92** [comment]
First version published on following commit https://github.com/Rapacademix/redbull/commit/bd2b97856d7ff047e4e7b4d12a7e2341709284bc
on `classify-rappers` branch

**Comment by LouisonGitzinger** [comment]
in your last commit your function seems to store multiple keywords so I assume you self-answered your question :D.

Review done for commit https://github.com/Rapacademix/redbull/commit/bd2b97856d7ff047e4e7b4d12a7e2341709284bc

**Comment by heus92** [comment]
Indeed ! I though that if match was true then we'd always have a basic word like *rap* or *rapper* and would eventually lose some finesse. Thus it felt smarter to keep all those words. 

Thanks for review 👌

**Comment by heus92** [comment]
New PR opened #6 to fix this issue

**Comment by LouisonGitzinger** [comment]
Can we close this issue ?

**Comment by heus92** [comment]
Yes sir 👍

**Comment by LouisonGitzinger** [comment]
It seems to be a good place to start a list of features we can take into account to classify an artist as a rapper or not

- [ ] Genius description

- [ ] Spotify artist genre

- [ ] Last.fm artist genre

- [ ] Wikipedia artist genre
